name: Run Cron Job

on:
  schedule:
    - cron: '0 * * * *'  # Every hour (UTC)
  workflow_dispatch:        # Cho phép chạy thủ công nếu muốn

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Wait for MySQL
        run: |
          echo "Waiting for MySQL to be ready..."
          sleep 15

      - name: Install dependencies
        run: npm install

      - name: Run script
        env:
          DB_HOST: mysql-156dd2ec-daip6690-896b.b.aivencloud.com
          DB_USER: avnadmin
          DB_PASS: AVNS_exd4hOEO2RJihoXspsp
          DB_NAME: bida
        run: npx ts-node --require tsconfig-paths/register run.ts
